{ config, pkgs, lib, userState, ... }:

{
  # Cafaye Foundation
  imports = [
    ./local-user.nix # Generated by installer
    
    # Core modules (these should be refactored to Home Manager)
    ./modules/interface/terminal.nix
    ./modules/interface/tools.nix
    ./modules/interface/theme.nix
    ./modules/interface/cli.nix
    ./modules/editors/neovim.nix
    
    # Optional modules based on userState
    ./modules/languages/ruby.nix
    ./modules/languages/python.nix
    ./modules/languages/nodejs.nix
    ./modules/languages/rust.nix
    ./modules/languages/go.nix
    
    ./modules/services/postgresql.nix
    ./modules/services/redis.nix
    
    ./modules/frameworks/rails.nix
    ./modules/frameworks/django.nix
    ./modules/frameworks/nextjs.nix
  ];

  # Home Manager needs a bit of info to work
  home.packages = with pkgs; [
    # Foundation tools
    git
    curl
    jq
    gum
  ];

  home.sessionVariables = {
    EDITOR = lib.mkForce (userState.editors.default or "nvim");
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
