{ config, pkgs, lib, userState, ... }:

let
  enabled = userState.interface.terminal.multiplexer.tmux.enable or true;
  
  # Helper to read optional config files
  readConfig = path: if builtins.pathExists path then builtins.readFile path else "";
  
  # Configuration layers
  defaultConfig = readConfig ../../../config/cafaye/tmux/tmux.conf;
  userConfig = readConfig ../../../config/user/tmux/tmux.conf;
in
{
  config = lib.mkIf enabled {
    programs.tmux = {
      enable = true;
      shell = "${pkgs.zsh}/bin/zsh";
      historyLimit = 50000;
      mouse = true;
      extraConfig = ''
        # ═══════════════════════════════════════════════════════════════════
        # CAFAYE TMUX CONFIGURATION
        # Managed by Nix/Home Manager - DO NOT EDIT THIS FILE DIRECTLY
        # ═══════════════════════════════════════════════════════════════════
        
        # --- [ LAYER 1: CAFAYE DEFAULTS ] ---
        ${defaultConfig}
        
        # --- [ LAYER 2: USER OVERRIDES ] ---
        ${userConfig}
      '';
    };

    # Link the theme script to the expected location
    xdg.configFile."tmux/base16.sh".source = ../../../config/user/tmux/base16.sh;
  };
}
