#!/bin/bash

# Reads a value from environment.json
# Usage: caf-state-read "languages.ruby"

if [[ -z "$STATE_FILE" ]]; then
    # New location as per DEVELOPMENT.md
    STATE_FILE="$HOME/.config/cafaye/environment.json"

    if [[ ! -f "$STATE_FILE" ]]; then
        # Local development fallback
        STATE_FILE="$(git rev-parse --show-toplevel 2>/dev/null)/environment.json"
    fi
fi

key="$1"
if [[ -f "$STATE_FILE" ]]; then
    jq -r ".$key" "$STATE_FILE"
else
    echo "null"
fi
